"""empty message

Revision ID: 8e216a359e06
Revises: 2db433572d4a
Create Date: 2022-10-17 22:32:50.929819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e216a359e06'
down_revision = '2db433572d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('imagen', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'imagen')
    # ### end Alembic commands ###
